### ISSUE TITLE
Put github instructions in front of omzsh instructions

### ISSUE THREAD

**Issue by waltspence** [jeanleonino/linux-checklist#19]
Git needs to be installed to complete omzh install via curl

![screenshot from 2015-11-13 13-09-25](https://cloud.githubusercontent.com/assets/328087/11153729/d8f4ef28-8a08-11e5-8575-f9d5deffc168.png)

**Comment by jeanlucaslima** [comment]
d3864a66a0cecfe897e97f5a23a79d1a5f8dec0d solves, thanks!

**Comment by jeanlucaslima** [comment]
Still... Needs more text explaining, should each part have the "apt-get" with the prerequisites?
